import type { NextPage } from 'next';
import Head from 'next/head';
import { Accordion, AccordionItem } from '@szhsin/react-accordion';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Accordion singleEnter transition timeout={300}>
          <AccordionItem
            header="header 1"
            itemKey="hello"
            className={({ state }) => (state === 'entered' ? 'open' : 'closed')}
          >
            content 1<textarea />
          </AccordionItem>
          <AccordionItem header="header 2" initialEntered>
            content 2<div>more</div>
            <Accordion>
              <AccordionItem header="header 1">content 1</AccordionItem>
              <AccordionItem header="header 2">
                content 2<div>more</div>
              </AccordionItem>
              <AccordionItem header="header 3">
                content 3<div>more</div>
                <div style={{ height: 500 }}>more</div>
              </AccordionItem>
            </Accordion>
          </AccordionItem>
          <AccordionItem header="header 3" itemKey={3}>
            content 3<div>more</div>
            <Accordion>
              <AccordionItem header="header 3.1">content 3.1</AccordionItem>
            </Accordion>
            <button>more</button>
          </AccordionItem>
        </Accordion>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
